### ISSUE TITLE
error: no such file or directory

### ISSUE THREAD

**Issue by winfredwyw** [tgreyuk/typedoc-plugin-markdown#139]
scripts:
`"doc": "typedoc --plugin typedoc-plugin-markdown"`

details:
`Error: ENOENT: no such file or directory, stat '/Users/bjhl/Desktop/WorkCode/utils-fe/node_modules/typedoc-plugin-markdown/dist/resources/assets'`

**Comment by tgreyuk** [comment]
@winfredwyw I'm not able to replicate with info provided. is there any more context (fuller stack trace etc) or better still an example in a repo?

**Comment by markbirbeck** [comment]
Same here.

Stack trace:

```shell
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc-plugin-markdown/dist/resources/assets'
    at Object.statSync (fs.js:1029:3)
    at Object.statSync (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/node_modules/graceful-fs/polyfills.js:307:34)
    at statSync (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/node_modules/fs-extra/lib/util/stat.js:49:33)
    at Object.copySync (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at AssetsPlugin.onRendererBegin (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/dist/lib/output/plugins/AssetsPlugin.js:28:16)
    at /Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/dist/lib/utils/events.js:259:33
    at triggerApi (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/dist/lib/utils/events.js:110:13)
    at Renderer.trigger (/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc/dist/lib/utils/events.js:252:13) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/markbirbeck/workspace/monorepo/packages/doc-generator/node_modules/typedoc-plugin-markdown/dist/resources/assets'
}
```

**Comment by markbirbeck** [comment]
Actually, I think there might be a simple explanation. :)

I'm using a JSON config file and before I decided to output Markdown, I was using the 'minimal' theme. That setting was still set. Removing it solved this problem. (Revealing a different problem...)

That probably doesn't explain @winfredwyw's problem, though.

**Comment by tgreyuk** [comment]
@markbirbeck thank you for the details.

**Comment by manix84** [comment]
I'm getting a simliar problem...

## The problem
```sh
$ npx typedoc './src' \
--out './dist/docs' \
--hideBreadcrumbs \
--hideGenerator \
--exclude '**/__tests__/*' \
--exclude '**/*.example.tsx' \
--plugin typedoc-plugin-markdown \
--theme ./.typedocs/themes/ThemeName
Loaded plugin typedoc-plugin-markdown

Using TypeScript 4.0.2 from /path/to/node_modules/typescript/lib
ENOENT: no such file or directory, stat '/path/to/node_modules/typedoc-plugin-markdown/dist/resources/assets'
```

The themes directory looks like this...
```
ThemeName
 ┣ layouts
 ┃ ┗ default.hbs
 ┣ partials
 ┃ ┣ comment.hbs
 ┃ ┣ footer.hbs
 ┃ ┣ header.hbs
 ┃ ┣ index.hbs
 ┃ ┣ member.declaration.hbs
 ┃ ┣ member.getterSetter.hbs
 ┃ ┣ member.hbs
 ┃ ┣ member.signature.body.hbs
 ┃ ┣ member.signature.title.hbs
 ┃ ┣ member.signatures.hbs
 ┃ ┣ member.sources.hbs
 ┃ ┣ members.group.hbs
 ┃ ┣ members.hbs
 ┃ ┣ navigation.hbs
 ┃ ┣ parameter.hbs
 ┃ ┣ type.hbs
 ┃ ┣ typeAndParent.hbs
 ┃ ┗ typeParameters.hbs
 ┗ templates
 ┃ ┣ index.hbs
 ┃ ┗ reflection.hbs
```

## The Reason...
All I'm looking to do is alter some of the URLs generated in the theme, eg:
```
## Index

### Properties

* [className](_common_baseprops_.basecomponentprops.md#optional-classname)
* [testID](_common_baseprops_.basecomponentprops.md#optional-testid)
```
will ideally be:
```
## Index

### Properties

* [className](#optional-classname)
* [testID](#optional-testid)
```

because i'm importing them into a custom library.

## Any other information...
Everything works until I add `--theme ./.typedocs/themes/ThemeName`, and then it complains about the plugin missing the assets. If I remove the plugin, and render with the theme, everything works, but it's rending into HTML files, and the markdown is missing it's newlines.

**Comment by tgreyuk** [comment]
The only reason that TypeDoc would be looking for an assets folder is if an html theme is being loaded as per @markbirbeck comments. I have made some additional checks so if the theme being loaded is not a recognised markdown theme the renderer will fallback to default markdown theme with a warning. 

@manix84 your issue is a bit different whereby you are trying to customise the theme.I think the key here may have been you were missing a theme.js file.  I have set-up and example repo of a very simple example of how to customise. https://github.com/tgreyuk/typedoc-markdown-demos/tree/master/demo-custom-theme . This also includes an example how you might configure the url as per your comments (see `helpers/relative-url.js` in the repo).
