### ISSUE TITLE
docusaurus-plugin-typedoc: Generated sidebar subcategories invalid references on MD files

### ISSUE THREAD

**Issue by petrleocompel** [tgreyuk/typedoc-plugin-markdown#214]
Generated "sidebar" has wrong file ids `docs/...` instead of `api/...`

## Error log 
```
Error: Bad sidebars file.
These sidebar document ids do not exist:
- docs/enums/datefilteritem

Available document ids=
- api/enums/datefilteritem 
```

## Directory structure (docs root)
```
docs
├── api <- Generated
│   ├── enums
│   │   ├── datefilteritem.md
│   ├── index.md
└── README.md
```

## typedoc-sidebar.js (generated)
```js
module.exports = [
  "docs/index",
  {
    "type": "category",
    "label": "Enumerations",
    "items": [
      "docs/enums/datefilteritem"
    ]
  }
}
```

## Docusaurus Plugin config
```
        [
            'docusaurus-plugin-typedoc',
            // Plugin / TypeDoc options
            {
                entryPoints: ['../src/index.ts'],
                tsconfig: '../tsconfig.json',
                watch: process.env.TYPEDOC_WATCH,

                docsRoot: 'docs',
                out: 'api',
                sidebar: {
                    sidebarFile: 'typedoc-sidebar.js',
                },
            },
        ]
```

# Current workaround
RN to make it work only think needed to change is in plugin config `out` to `docs`. 
My Generated docs will be in `docs/docs` instead of `docs/api` but it works.

By README docs in lib `out` parameter should be used as prefix for urls in `sidebar` but it seems like `docsRoot` is beeing used.

Further invertigation will be needed.

**Comment by petrleocompel** [comment]
:exploding_head: :warning: "parameters are merged with tsconfig.json" (`typedocOptions`) 
My `tsconfig.json` contained `"out": "docs"` and this made this problem.

I suggest to make some "check" if `tsconfig.json` contains `typedocOptions` and if props are defined in both i guess minimally warn in log ? 

Because of this i miss kinda who has the higher ground `tsconfig` or config of plugin?

**Comment by tgreyuk** [comment]
@petrleocompel Thanks for this and the follow up information. 

There is actually an additional bug going on here because the sidebars and the TypeDoc renderer were using different params (which is why it threw an error rather than just publishing to the unexpected directory). So i have fixed that issue. 

Checking the options from multiple places with a warning is a sensible idea but actually not very easy to implement it in a clean way. However I have updated the Readme to make the priority of options more explicit.
