### ISSUE TITLE
docusaurus: Remove/Hide "Modules" folder

### ISSUE THREAD

**Issue by yiliansource** [tgreyuk/typedoc-plugin-markdown#238]
Is it possible to stop the "Modules" folder from being generated? I do not really see an advantage in having those, since they just contain a single item most of the time. Or am I missing a usecase there?

![image](https://user-images.githubusercontent.com/41469451/122907862-d6894a00-d353-11eb-873d-cab4d7a0de26.png)

**Comment by tgreyuk** [comment]
You may get a better outcome by specifying files rather than directory in your entryPoints:

ie specifying `./src` will treat every all files in the directory as an entryPoint which is why you are seeing each class as a separate module. However specifying something like [`src/component/index`,'folder-b/index] will hoist all exports into 'components' .

**Comment by yiliansource** [comment]
Since the config is just Javascript I could just dynamically get all the file names, hmm... I'll play around with that tomorrow and report back!

**Comment by tgreyuk** [comment]
Yeah - although you will just want to get all the index files (which will then export all the items of the given module).

**Comment by yiliansource** [comment]
That worked beautifully!

I now ended up with a Table of contents file and a namespaces folder, which is a lot cleaner than what I previously had. Thanks again for the help and the great tool!

![image](https://user-images.githubusercontent.com/41469451/123065004-0cd7cf80-d40f-11eb-8ff0-83dff89e2dff.png)

```js
const glob = require("glob");
// ...
entryPoints: glob.sync("../src/**/index.ts"),
```
