### ISSUE TITLE
namedAnchors not having any effect, bitbucket compatibility

### ISSUE THREAD

**Issue by anantoghosh** [tgreyuk/typedoc-plugin-markdown#277]
Hi @tgreyuk,

I'm trying to use typedoc-plugin-markdown to generate markdown doc for bitbucket cloud.

The anchors in the TOC do not work in bitbucket.

I tried using `--namedAnchors` but it does not seem to have any effect on the generated docs.

I've added the repo for you to check out, docs folder has the regular output and named-docs has the output with `--namedAnchors`
I've also added the same repo to bitbucket.
- https://github.com/anantoghosh/typedoc-md-issue
- https://bitbucket.org/anantoghosh/typedoc-md-issue/src/main/

and thank you for your work in this project.

**Comment by tgreyuk** [comment]
Hi @anantoghosh .. thanks that option seems to have gotten removed in a previous refactor. But actually I don't think that will help you because (the last time i looked) bitbucket cloud escapes html. I did create another package to fix bitbucket cloud anchor headers which i think should help you. https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/typedoc-bitbucket-theme

**Comment by anantoghosh** [comment]
Hi thank you @tgreyuk , I'll try `typedoc-bitbucket-theme`. I had seen that package name, but I thought it was related to html docs theming 🤦‍♂️ .
