### ISSUE TITLE
[next] Some types are not getting output

### ISSUE THREAD

**Issue by ziad-saab** [tgreyuk/typedoc-plugin-markdown#470]
You can see an example of types not being output here:

https://docs.metamask.io/zs/keyring-doc/snaps/reference/keyring-api/Type%20Aliases/type-alias.Keyring/

The output looks like this:

<img width="1005" alt="image" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/3943143/69c2c67b-021e-418a-b487-823154446aba">

**Comment by tgreyuk** [comment]
## Fix versions

typedoc-plugin-markdown@4.0.0-next.21
docusaurus-plugin-typedoc@1.0.0-next.16

## Changes

The full docs for the type is now correctly exposed under the 'Type declaration' heading (as per html theme)

<img width="835" alt="Screenshot 2023-09-25 at 22 57 35" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/11680870/8e4a1f9e-2d50-44e2-92fc-6b6ba4bc5e3f">

You will notice that type inside the declaration is collapsed to the word 'object'. This is because the expanded object is very large, but it can be expanded by the option `expandObjects:true` which will produce output as follows:

<img width="651" alt="Screenshot 2023-09-25 at 23 03 59" src="https://github.com/tgreyuk/typedoc-plugin-markdown/assets/11680870/05c446a9-24c2-4a5e-a1dc-bd403428438a">
